name: r_w_r
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  exprollable_page_view: ^1.0.3
  http: ^1.3.0
  video_player: ^2.9.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.1.1
  #  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.2
  fl_chart: ^0.71.0
  speedometer_chart: ^1.0.8
  share_plus: ^11.0.0
  razorpay_flutter: ^1.4.0
  #  file_picker: ^10.1.6
  permission_handler: ^12.0.0+1
  intl: any
  flutter_pdfview: ^1.4.0+1
  path_provider: ^2.1.5
  geolocator: 13.0.4
  firebase_core: ^3.13.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.13.0
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.1
  dropdown_search: ^6.0.2
  google_maps_flutter: ^2.12.2
  uuid: ^4.5.1
  glob: ^2.1.3
  #  google_mlkit_face_detection: ^0.13.1
  #  dropdown_search: ^6.0.2
  #  google_maps_flutter: ^2.12.2
  #  uuid: ^4.5.1
  #  glob: ^2.1.3
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  web_socket_channel: ^3.0.3
  flutter_html: ^3.0.0
  #  path: ^1.9.1
  google_ml_kit: ^0.20.0
  #  geocoding: ^4.0.0
  printing: ^5.14.2
  #  pdf: ^3.11.3
  flutter_widget_from_html_core: ^0.16.0
  #  image: ^4.5.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.4
  geocoding: ^4.0.0
  image_cropper: ^8.0.2
  path: ^1.9.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter configuration section
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/svg/
    - assets/config/

#flutter_intl:
#  enabled: true
#  arb_dir: lib/l10n
#  template_arb_file: app_en.arb
#  output_localization_file: app_localizations.dart
#  output_dir: lib/l10n
#  untranslated_messages_file: lib/l10n/untranslated_messages.json